name: 'Create SwiftFormat Report Page'
description: 'Converts a SwiftFormat JSON report to a Markdown file for Jekyll.'

runs:
  using: "composite"
  steps:
    - name: 'Check for Homebrew and install if not present'
      shell: bash
      run: |
        if ! command -v brew &> /dev/null; then
          echo "Homebrew not found. Installing..."
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo "/opt/homebrew/bin" >> $GITHUB_PATH
        else
          echo "Homebrew is already installed."
        fi

    - name: 'Install SwiftFormat'
      shell: bash
      run: |
        brew install swiftformat
        echo "SwiftFormat installed."

    - name: Run SwiftFormat. Generate JSON data
      shell: bash
      continue-on-error: true
      run: |
        swiftformat . --lint --reporter json > ./swiftformat-report.json

    - name: Create output directory
      shell: bash
      run: mkdir -p swiftformat-artifact

    - name: Generate HTML from JSON using Python
      shell: bash
      run: |
        python ${{ github.action_path }}/generate_swiftformat_report.py \
          --json-path "./swiftformat-report.json" \
          --output-path "./swiftformat-artifact/swiftformat-report.html" \
          --github-workspace "${{ github.workspace }}"

    - name: Create md page for the report
      shell: bash
      run: |
        cat <<EOF > "swiftformat-artifact/index.md"
        ---
        layout: default
        title: SwiftFormat Style Report
        ---
        <iframe src="swiftformat-report.html" style="width: 100%; height: calc(93vh); border: none;"></iframe>
        EOF

    - name: Upload SwiftFormat artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: swiftformat-report
        path: swiftformat-artifact
        retention-days: 7