= SwiftFormat
:source-highlighter: highlight.js

== Что это?

SwiftFormat — это библиотека кода и инструмент командной строки для переформатирования кода Swift на macOS, Linux или Windows.

SwiftFormat выходит за рамки того, что вы могли бы ожидать от форматера кода. Помимо настройки пробелов, он может вставлять или удалять неявное `self`, удалять избыточные скобки и исправлять многие другие отклонения от стандартных идиом Swift.

== Зачем мне это нужно?

Многие программисты имеют предпочтительный стиль форматирования своего кода, а другие, кажется, совершенно не замечают существующих соглашений о форматировании в проекте (к ярости своих коллег).

При совместной работе над проектом полезно договориться об общем стиле кодирования, но enforcing это вручную утомительно и чревато ошибками, и может привести к спорам, если некоторые участники относятся к этому более серьезно, чем другие.

Наличие инструмента для автоматического применения общего стиля устраняет эти проблемы и позволяет вам сосредоточиться на поведении кода, а не на его представлении.

== Как мне его установить?

Это зависит от ситуации — есть несколько способов использования SwiftFormat:

*   Как инструмент командной строки, который вы запускаете вручную или как часть другой цепочки инструментов
*   Как расширение редактора исходного кода, которое можно вызвать через меню Editor > SwiftFormat в Xcode
*   Как фазу сборки в вашем проекте Xcode, чтобы он запускался каждый раз, когда вы нажимаете Cmd-R или Cmd-B, или
*   Как pre-commit хук Git, чтобы он запускался для всех измененных файлов перед их коммитом

=== Инструмент командной строки

==== Установка:

Вы можете установить инструмент командной строки `swiftformat` на macOS или Linux с помощью Homebrew. Предполагая, что у вас уже установлен Homebrew, просто введите:

[source,bash]
----
$ brew install swiftformat
----

Чтобы обновиться до последней версии после установки:

[source,bash]
----
$ brew upgrade swiftformat
----

Кроме того, вы можете установить инструмент на macOS или Linux, используя Mint следующим образом:

[source,bash]
----
$ mint install nicklockwood/SwiftFormat
----

Или, если хотите, вы можете скачать и собрать SwiftFormat вручную на macOS, Linux или Windows следующим образом:

[source,bash]
----
$ git clone https://github.com/nicklockwood/SwiftFormat
$ cd SwiftFormat
$ swift build -c release
----

Если вы устанавливаете SwiftFormat в каталог вашего проекта, вы можете использовать CocoaPods на macOS для автоматической установки бинарного файла `swiftformat` вместе с другими подами — подробности см. в инструкциях по фазе сборки Xcode ниже.

Другой вариант — включить бинарный `artifactbundle` в ваш `Package.swift`:

[source,swift]
----
.binaryTarget(
    name: "swiftformat",
    url: "https://github.com/nicklockwood/SwiftFormat/releases/download/0.55.0/swiftformat-macos.artifactbundle.zip",
    checksum: "CHECKSUM"
),
----

Если вы предпочитаете не использовать менеджер пакетов, вы можете собрать приложение командной строки вручную:

1.  Откройте `SwiftFormat.xcodeproj` и соберите схему `SwiftFormat (Application)`.
2.  Перетащите бинарный файл `swiftformat` в `/usr/local/bin/` (это скрытая папка, но вы можете использовать меню Finder's Go > Go to Folder... для ее открытия).
3.  Откройте `~/.bash_profile` в вашем любимом текстовом редакторе (это скрытый файл, но вы можете ввести `open ~/.bash_profile` в терминале, чтобы открыть его).
4.  Добавьте следующую строку в файл: `alias swiftformat="/usr/local/bin/swiftformat --indent 4"` (вы можете опустить `--indent 4` или заменить его чем-то другим. Запустите `swiftformat --help`, чтобы увидеть доступные опции).
5.  Сохраните файл `.bash_profile` и выполните команду `source ~/.bash_profile`, чтобы изменения вступили в силу.

==== Использование:

Если вы следовали инструкциям по установке выше, теперь вы можете просто ввести

[source,bash]
----
$ swiftformat .
----

(это пробел, а затем точка после команды) в терминале, чтобы отформатировать любые файлы Swift в текущем каталоге. Вместо `.` вы можете ввести абсолютный или относительный путь к файлу или каталогу, который вы хотите отформатировать.

WARNING: `swiftformat .` перезапишет все найденные файлы Swift в текущем каталоге и во всех его подпапках. Если вы запустите его в своем домашнем каталоге, он, вероятно, переформатирует каждый файл Swift на вашем жестком диске.

Чтобы использовать его безопасно, сделайте следующее:

1.  Выберите файл или каталог, к которому вы хотите применить изменения.
2.  Убедитесь, что вы закоммитили все свои изменения в этом коде в git (или в любой другой системе контроля версий, которую вы используете).
3.  (Необязательно) В терминале введите `swiftformat --infer-options "/path/to/your/code/"`. Это предложит набор опций форматирования, которые соответствуют вашему существующему стилю проекта (но вы можете игнорировать их и использовать значения по умолчанию или свои собственные настройки, если хотите).

Путь может указывать как на один файл Swift, так и на каталог с файлами. Он может быть абсолютным или относительным к текущему каталогу. Кавычки `""` вокруг пути необязательны, но если путь содержит пробелы, вам нужно либо использовать кавычки, либо экранировать каждый пробел с помощью `\`. Вы можете указать несколько путей, разделенных пробелами.

4.  В терминале введите `swiftformat "/path/to/your/code/"`. Те же правила применяются к путям, и разрешены несколько путей, разделенных пробелами.

Если вы использовали `--infer-options` для генерации предложенного набора опций на шаге 3, вы должны скопировать и вставить их в команду, либо до, либо после пути(ей) к вашим исходным файлам.

Если вы создали файл конфигурации, вы можете указать его путь с помощью `--config "/path/to/your/config-file/"`. В качестве альтернативы, если вы назовете файл `.swiftformat` и поместите его в проект, который вы форматируете, он будет автоматически подхвачен.

5.  Нажмите enter, чтобы начать форматирование. После завершения форматирования используйте вашу систему контроля версий, чтобы проверить изменения и убедиться, что не было внесено нежелательных изменений. Если они есть, отмените изменения, настройте опции и попробуйте снова.
6.  (Необязательно) закоммитьте изменения.

Следование этим инструкциям должно гарантировать, что вы избежите катастрофической потери данных, но в маловероятном случае, если это сотрет ваш жесткий диск, обратите внимание, что я не несу никакой ответственности.

==== Использование стандартного ввода/вывода:

Если вы предпочитаете, вы можете использовать unix-пайпы, чтобы включить SwiftFormat в цепочку команд. Например, это альтернативный способ форматирования файла:

[source,bash]
----
$ cat /path/to/file.swift | swiftformat --output /path/to/file.swift
----

Опущение `--output /path/to/file.swift` выведет отформатированный файл на стандартный вывод (stdout). Вы также можете явно передать "stdout" в качестве пути вывода:

[source,bash]
----
$ cat /path/to/file.swift | swiftformat --output stdout
----

Или вы можете использовать `>` для указания пути вывода следующим образом:

[source,bash]
----
$ cat /path/to/file.swift | swiftformat > /path/to/file.swift
----

Если вы не укажете входной файл, SwiftFormat автоматически будет принимать ввод со стандартного ввода (stdin), но истечет время ожидания, если ввод не будет получен немедленно, и отобразит экран справки. Чтобы сделать это явно, передайте "stdin" в качестве пути ввода:

[source,bash]
----
$ cat /path/to/file.swift | swiftformat stdin
----

При использовании stdin SwiftFormat не имеет доступа к пути файла ввода, поэтому функции, которые зависят от местоположения файла (например, вставка даты создания в комментарии заголовка или обнаружение файлов конфигурации `.swiftformat` в пути файла), не будут работать. Чтобы решить эту проблему, вы можете указать путь к файлу с помощью аргумента `--stdin-path`:

[source,bash]
----
$ cat /path/to/file.swift | swiftformat stdin --stdinpath /path/to/file.swift
----

=== Расширение редактора исходного кода Xcode

==== Установка:

Как и инструмент командной строки, вы можете установить расширение SwiftFormat for Xcode через Homebrew. Предполагая, что у вас уже установлен Homebrew, введите:

[source,bash]
----
$ brew install --cask swiftformat-for-xcode
----

Это установит SwiftFormat for Xcode в вашу папку Applications. Дважды щелкните приложение, чтобы запустить его, а затем следуйте инструкциям на экране.

NOTE: Приложение должно быть правильно подписано, но если вы получаете предупреждение Gatekeeper при попытке его открыть, вы можете обойти это, щелкнув правой кнопкой мыши (или control-щелчком) по приложению и выбрав Open.

Чтобы обновиться до последней версии после установки, используйте:

[source,bash]
----
$ brew upgrade --cask swiftformat-for-xcode
----

В качестве альтернативы, если вы предпочитаете не использовать Homebrew, вы найдете последнюю версию приложения SwiftFormat for Xcode на странице релизов GitHub. Загрузите и распакуйте zip-архив, затем перетащите `SwiftFormat for Xcode.app` в папку Applications.

==== Использование:

После того, как вы запустили приложение и перезапустили Xcode, вы найдете опцию SwiftFormat в меню Editor Xcode. Если меню SwiftFormat не появляется, эта ветка может помочь.

Вы можете настроить правила и опции форматирования с помощью хост-приложения SwiftFormat for Xcode. В настоящее время нет способа переопределить их для каждого проекта, однако вы можете импортировать и экспортировать различные конфигурации с помощью меню File. Вам нужно будет делать это каждый раз, когда вы переключаетесь между проектами.

Формат файла конфигурации описан в разделе Config ниже.

Note: SwiftFormat for Xcode не может автоматически обнаруживать изменения в импортированном файле конфигурации. Если вы обновите файл `.swiftformat` для своего проекта, вам нужно будет вручную повторно импортировать этот файл в SwiftFormat for Xcode, чтобы расширение редактора исходного кода Xcode использовало новую конфигурацию.

=== Фаза сборки Xcode

NOTE: Добавление этого скрипта перезапишет ваши исходные файлы по мере работы с ними, что имеет неприятный побочный эффект очистки истории отмены. Вы можете добавить скрипт к вашей тестовой цели, а не к основной, чтобы он вызывался только при запуске юнит-тестов, а не при каждой сборке приложения.

В качестве альтернативы, вы можете рассмотреть возможность запуска SwiftFormat в режиме `lint` как часть вашей обычной сборки, а затем запускать проход форматирования вручную или как часть менее частой цели сборки (например, тестов).

==== Использование Swift Package Manager

Чтобы настроить SwiftFormat как фазу сборки Xcode, сделайте следующее:

1) Создайте папку `BuildTools` и `Package.swift`

*   Создайте папку с именем `BuildTools` в той же папке, что и ваш файл `xcodeproj`.
*   В этой папке создайте файл с именем `Package.swift` со следующим содержимым:

[source,swift]
----
// swift-tools-version:5.1
import PackageDescription

let package = Package(
    name: "BuildTools",
    platforms: [.macOS(.v10_11)],
    dependencies: [
        .package(url: "https://github.com/nicklockwood/SwiftFormat", from: "0.58.5"),
    ],
    targets: [.target(name: "BuildTools", path: "")]
)
----

*   Если вы используете Xcode 11.4 или новее, в папке `BuildTools` создайте файл с именем `Empty.swift` без содержимого. Это необходимо для удовлетворения изменений в Swift Package Manager.

2) Добавьте фазу сборки в вашу цель приложения

*   Нажмите на свой проект в списке файлов, выберите свою цель в разделе `TARGETS`, перейдите на вкладку `Build Phases`.
*   Добавьте `New Run Script Phase`, нажав на маленький значок плюса в левом верхнем углу.
*   Снимите флажок `Based on dependency analysis`.
*   Перетащите новую фазу `Run Script` над фазой `Compile Sources`, разверните ее и вставьте следующий скрипт:

[source,bash]
----
cd BuildTools
SDKROOT=$(xcrun --sdk macosx --show-sdk-path)
#swift package update #Раскомментируйте эту строку временно, чтобы обновить используемую версию до последней, соответствующей вашему файлу BuildTools/Package.swift
swift run -c release swiftformat "$SRCROOT"
----

Вы также можете использовать `swift run -c release --package-path BuildTools swiftformat "$SRCROOT"`, если вам нужен более сложный скрипт и `cd BuildTools` что-то ломает.

NOTE: Вы можете захотеть закоммитить `BuildTools/Package.swift` в вашу систему контроля версий, чтобы версия, используемая вашей фазой запуска скрипта, оставалась под контролем версий. Рекомендуется добавить следующее в ваш файл `.gitignore`: `BuildTools/.build` и `BuildTools/.swiftpm`.

NOTE (2): Если вы используете Xcode 15 или новее, убедитесь, что опция `ENABLE_USER_SCRIPT_SANDBOXING` (также известная как "User Script Sandboxing") установлена в `NO`, иначе SwiftFormat не сможет работать корректно.

==== Использование CocoaPods

1) Добавьте SwiftFormat CLI в ваш `Podfile`

Добавьте бинарный файл `swiftformat` в ваш проект через CocoaPods, добавив следующую строку в ваш `Podfile`, а затем запустив `pod install`:

[source,ruby]
----
pod 'SwiftFormat/CLI', '~> 0.58.5'
----

NOTE: Это установит только предварительно собранное приложение командной строки, а не исходный код фреймворка SwiftFormat.

NOTE (2): При установке таким способом GateKeeper может заблокировать запуск `swiftformat` до тех пор, пока вы не откроете его вручную в первый раз, щелкнув правой кнопкой мыши в Finder и выбрав "Open".

2) Добавьте фазу сборки в вашу цель приложения

*   Нажмите на свой проект в списке файлов, выберите свою цель в разделе `TARGETS`, перейдите на вкладку `Build Phases`.
*   Добавьте `New Run Script Phase`, нажав на маленький значок плюса в левом верхнем углу.
*   Снимите флажок `Based on dependency analysis`.
*   Перетащите новую фазу `Run Script` над фазой `Compile Sources`, разверните ее и вставьте следующий скрипт:

[source,bash]
----
"${PODS_ROOT}/SwiftFormat/CommandLineTool/swiftformat" "$SRCROOT"
----

==== Альтернатива: Локально установленный SwiftFormat

В качестве альтернативы вы можете использовать локально установленный инструмент командной строки `swiftformat`, поместив следующее в вашу фазу `Run Script`:

[source,bash]
----
if which swiftformat >/dev/null; then
  swiftformat .
else
  echo "warning: SwiftFormat not installed, download from https://github.com/nicklockwood/SwiftFormat"
fi
----

Однако это не рекомендуется для общих проектов, так как разные члены команды, использующие разные версии SwiftFormat, могут привести к шуму в истории коммитов из-за непоследовательного форматирования кода.

Если вы установили SwiftFormat через Homebrew на Apple Silicon, вы можете столкнуться с этим предупреждением:

`warning: SwiftFormat not installed, download from https://github.com/nicklockwood/SwiftFormat`

Это связано с тем, что Homebrew на Apple Silicon по умолчанию устанавливает бинарные файлы в папку `/opt/homebrew/bin`. Чтобы указать Xcode, где найти SwiftFormat, вы можете либо добавить `/opt/homebrew/bin` в переменную окружения `PATH` в вашей фазе сборки:

[source,bash]
----
if [[ "$(uname -m)" == arm64 ]]; then
    export PATH="/opt/homebrew/bin:$PATH"
fi

if which swiftformat > /dev/null; then
  swiftformat .
else
  echo "warning: SwiftFormat not installed, download from https://github.com/nicklockwood/SwiftFormat"
fi
----

либо вы можете создать символическую ссылку в `/usr/local/bin`, указывающую на фактический бинарный файл:

[source,bash]
----
ln -s /opt/homebrew/bin/swiftformat /usr/local/bin/swiftformat
----

=== Плагин Swift Package Manager

Вы можете использовать SwiftFormat как плагин команд SwiftPM.

NOTE: Требуется Swift 5.6 или выше. Добавьте пакет в ваши зависимости в файле `Package.swift`.

[source,swift]
----
dependencies: [
    // ...
    .package(url: "https://github.com/nicklockwood/SwiftFormat", from: "0.58.5"),
]
----

Плагин найдет существующий `.swiftformat` в корневой папке вашего пакета и автоматически его учтет.

==== Запуск плагина из командной строки

[source,bash]
----
swift package plugin --allow-writing-to-package-directory swiftformat
----

Вы можете ограничить форматирование определенной цели с помощью опции `--target`.

Вы также можете указать аргументы SwiftFormat, например, `--swift-version`.

Пример:

[source,bash]
----
swift package plugin --allow-writing-to-package-directory swiftformat --target MyLibrary --swift-version 5.6 --verbose
----

==== Запуск плагина из Xcode

В Xcode 14 вы можете запустить выполнение плагина для Swift-пакета или проекта Xcode.

Для проекта Xcode будет обработан основной каталог проекта, а опция `--target` будет проигнорирована.

Вы также можете указать аргументы SwiftFormat, например, `--swift-version`.

=== Через AppleScript

Чтобы запустить SwiftFormat для самого верхнего документа Xcode (проекта или рабочего пространства), вы можете использовать следующий AppleScript:

[source,applescript]
----
tell application "Xcode"
    set frontWindow to the first window
    set myPath to path of document of frontWindow
    do shell script "cd " & myPath & ";cd ..; /usr/local/bin/swiftformat ."
end tell
----

Некоторые приложения, из которых вы можете это запустить, — BetterTouchTool, Alfred или Keyboard Maestro. Другой вариант — определить QuickAction для Xcode через Automator, а затем назначить для него сочетание клавиш в системных настройках.

=== Плагин для VSCode

Если вы предпочитаете использовать редактор VSCode от Microsoft для написания на Swift, Valentin Knabel создал плагин для SwiftFormat.

=== Плагин для Sublime Text

Если вы предпочитаете использовать редактор Sublime Text, попробуйте плагин Sublime-Swift-Format от Aerobounce.

=== Плагин для Nova

Если вы предпочитаете использовать редактор Nova, попробуйте расширение SwiftFormat от Pádraig Ó Cinnéide.

=== Git pre-commit hook

1.  Следуйте инструкциям по установке инструмента командной строки SwiftFormat.
2.  Установите `git-format-staged`.
3.  Отредактируйте или создайте файл `.git/hooks/pre-commit` в папке вашего проекта. Папка `.git` скрыта, но должна уже существовать, если вы используете Git с вашим проектом, поэтому откройте ее через терминал или меню Finder's Go > Go to Folder....
4.  Добавьте следующую строку в файл `pre-commit`. `{}` будет автоматически заменен путем к форматируемому файлу Swift:

[source,bash]
----
#!/bin/bash
git-format-staged --formatter "swiftformat stdin --stdin-path '{}'" "*.swift"
----

(Обратите внимание, что этот пример использует вашу локально установленную версию SwiftFormat, а не отдельную копию в репозитории вашего проекта. Вы можете заменить `swiftformat` путем к копии внутри вашего проекта, если хотите.)

5.  Включите хук, введя `chmod +x .git/hooks/pre-commit` в терминале.

Теперь pre-commit хук будет запускаться каждый раз, когда вы выполняете `git commit`. Выполнение `git commit --no-verify` пропустит pre-commit хук.

NOTE: Если вы используете Git через графический клиент, такой как Tower, могут потребоваться дополнительные шаги.

NOTE (2): В отличие от подхода с фазой сборки Xcode, git pre-commit хук не будет закоммичен в систему контроля версий, и нет способа гарантировать, что все пользователи проекта используют одну и ту же версию SwiftFormat. Для совместного проекта вы можете рассмотреть возможность использования post-commit хука, который будет запускаться на вашем сервере непрерывной интеграции.

=== GitHub Actions

SwiftFormat предустановлен на всех раннерах GitHub-hosted для macOS. Если вы используете self-hosted, вам нужно будет убедиться, что SwiftFormat установлен на вашем раннере.

Создайте рабочий процесс GitHub Actions с использованием SwiftFormat, передав опцию командной строки `--reporter github-actions-log`. Следующий пример действия проверяет пул-реквесты с помощью SwiftFormat, сообщая о предупреждениях с помощью лога GitHub Actions.

[source,yaml]
----
# Lint.yml
name: Lint
on: pull_request

jobs:
  Lint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: SwiftFormat
        run: swiftformat --lint . --reporter github-actions-log
----

=== На CI с использованием Danger

Чтобы настроить SwiftFormat для использования вашей системой непрерывной интеграции с помощью Danger, сделайте следующее:

1.  Следуйте инструкциям по настройке Danger.
2.  Добавьте плагин `danger-swiftformat` в ваш `Gemfile`.
3.  Добавьте следующее в ваш `Dangerfile`:

[source,ruby]
----
swiftformat.binary_path = "/path/to/swiftformat" # опционально
swiftformat.additional_args = "--indent tab --self insert" # опционально
swiftformat.check_format(fail_on_error: true)
----

NOTE: Рекомендуется добавить бинарный файл `swiftformat` в каталог вашего проекта, чтобы гарантировать использование одной и той же версии каждый раз (см. инструкции по фазе сборки Xcode выше).

=== Сборка с Bazel

Если вы используете Bazel для сборки ваших Swift-проектов и хотите убедиться, что в вашу основную ветку попадает только правильно отформатированный код, попробуйте `rules_swiftformat`. Репозиторий содержит правила и макросы Bazel, которые форматируют исходные файлы Swift с помощью SwiftFormat, проверяют, что отформатированные файлы существуют в рабочем каталоге, и копируют отформатированные файлы в рабочий каталог.

=== Docker

SwiftFormat публикует релизы в реестре Docker GitHub Packages. Чтобы загрузить образ, вызовите:

[source,bash]
----
$ docker pull ghcr.io/nicklockwood/swiftformat:latest
----

По умолчанию контейнер запускает `swiftformat .`. Поэтому вам нужно указать путь либо через аргумент:

[source,bash]
----
docker run --rm -v /local/source/path:/work ghcr.io/nicklockwood/swiftformat:latest /work
----

либо изменив рабочий каталог:

[source,bash]
----
docker run --rm -v /local/source/path:/work -w /work ghcr.io/nicklockwood/swiftformat:latest
----

Чтобы проверить установленную версию SwiftFormat:

[source,bash]
----
docker run --rm ghcr.io/nicklockwood/swiftformat:latest --version
----

Пример линтинга:

[source,bash]
----
docker run --rm -v /local/source/path:/work ghcr.io/nicklockwood/swiftformat:latest /work --lint
----

== Конфигурация

Конфигурация SwiftFormat разделена на правила и опции. Правила — это функции в библиотеке SwiftFormat, которые применяют изменения к коду. Опции — это настройки, которые управляют поведением правил.

=== Опции

Доступные в SwiftFormat опции можно отобразить с помощью аргумента командной строки `--options`. Значение по умолчанию для каждой опции указано в тексте справки.

Правила настраиваются путем добавления `--[option_name] [value]` в ваши аргументы командной строки или путем создания файла конфигурации `.swiftformat` и размещения его в каталоге вашего проекта.

Данная опция может влиять на несколько правил. Используйте команду `--rule-info [rule_name]` для получения подробной информации о том, какие опции влияют на данное правило, или см. файл `Rules.md`.

Вы можете настроить опции для определенных файлов или диапазонов кода, используя директиву `swiftformat:options` в комментариях внутри вашего файла Swift. Чтобы временно установить одну или несколько опций внутри исходного файла, используйте:

[source,swift]
----
// swiftformat:options --indent 2 --allman true
----

Чтобы применить переопределение опций только к определенной строке, используйте модификаторы `:this`, `:next` или `:previous`:

[source,swift]
----
let indexUrl: URL // swiftformat:options:this --preserve-acronyms url

// swiftformat:options:next --semicolons inline
doTheThing(); print("Did the thing")
----

=== Правила

SwiftFormat включает более 50 правил, и новые добавляются постоянно. Актуальный список можно найти в `Rules.md` вместе с документацией по их использованию.

Список доступных правил можно отобразить в приложении командной строки с помощью аргумента `--rules`. Правила могут быть либо включены, либо выключены. Большинство из них включены по умолчанию. Отключенные правила помечаются как `(disabled)` при отображении с помощью `--rules`.

Вы можете использовать команду `--rule-info [rule_name]` для получения информации о конкретном правиле. Передайте список имен правил, разделенных запятыми, чтобы получить информацию для нескольких правил сразу, или используйте `--rule-info` без аргумента для получения информации обо всех правилах.

Вы можете отключать правила по отдельности, используя `--disable`, за которым следует список одного или нескольких имен правил, разделенных запятыми, или включать опциональные правила, используя `--enable`, за которым следуют имена правил:

[source,bash]
----
--disable redundantSelf,trailingClosures
--enable isEmpty
----

Если вы предпочитаете, вы можете использовать несколько аргументов `--enable`/`--disable` вместо использования запятых:

[source,bash]
----
--disable indent
--disable linebreaks
--disable redundantSelf
----

В качестве альтернативы вы можете использовать символ продолжения строки `\` для переноса одного аргумента на несколько строк:

[source,bash]
----
--disable          \
    indent,        \
    linebreaks,    \
    redundantSelf
----

Чтобы избежать автоматического включения новых правил при обновлении SwiftFormat, вы можете отключить все правила с помощью:

[source,bash]
----
--disable all
----

А затем индивидуально включить только те правила, которые вам нужны. В качестве альтернативы используйте аргумент `--rules`, чтобы включить только указанные вами правила:

[source,bash]
----
--rules indent,linebreaks
----

Как и выше, вы можете включить несколько аргументов `--rules` или использовать символ продолжения строки `\` для переноса правил на отдельные строки:

[source,bash]
----
--rules redundantSelf
--rules         \
    indent,     \
    linebreaks
----

Чтобы точно увидеть, какие правила были применены к данному файлу, вы можете использовать опцию командной строки `--verbose`, чтобы заставить SwiftFormat печатать более подробный лог по мере применения форматирования. NOTE: запуск в подробном режиме медленнее, чем в режиме по умолчанию.

Вы можете отключать правила для определенных файлов или диапазонов кода, используя директивы `swiftformat:` в комментариях внутри вашего файла Swift. Чтобы временно отключить одно или несколько правил внутри исходного файла, используйте:

[source,swift]
----
// swiftformat:disable <rule1> [<rule2> [rule<3> ...]]
----

Чтобы снова включить правило(а), используйте:

[source,swift]
----
// swiftformat:enable <rule1> [<rule2> [rule<3> ...]]
----

Чтобы отключить все правила, используйте:

[source,swift]
----
// swiftformat:disable all
----

И чтобы снова включить их все, используйте:

[source,swift]
----
// swiftformat:enable all
----

Чтобы временно предотвратить применение одного или нескольких правил только к следующей строке, используйте:

[source,swift]
----
// swiftformat:disable:next <rule1> [<rule2> [rule<3> ...]]
let foo = bar // правило(а) будет отключено для этой строки
let bar = baz // правило(а) будет снова включено для этой строки
----

Вы также можете использовать `this` или `previous` для включения или отключения правил для текущей или предыдущей строки. Нет необходимости вручную снова включать правило после использования директив `next`, `this` или `previous`.

NOTE: Директива `swiftformat:enable` служит только для отмены предыдущей директивы `swiftformat:disable` в том же файле. Невозможно использовать `swiftformat:enable` для включения правила, которое не было уже включено при запуске форматирования.

=== Файл конфигурации

Хотя можно настроить SwiftFormat напрямую с помощью опций командной строки и правил, описанных выше, иногда удобнее создать файл конфигурации, который можно добавить в ваш проект и поделиться с другими разработчиками.

Файл конфигурации SwiftFormat состоит из одной или нескольких опций командной строки, разделенных на отдельные строки, например:

[source]
----
--allman true
--indent tab
--disable elseOnSameLine,semicolons
----

Во время форматирования SwiftFormat автоматически проверит каждый подкаталог на наличие файла `.swiftformat` и применит любые найденные там опции к файлам в этом каталоге.

Это позволяет вам переопределять определенные правила или опции форматирования только для определенного каталога файлов. Вы также можете указать исключенные файлы относительно этого каталога с помощью `--exclude`, что может быть удобнее, чем указывать их на верхнем уровне:

[source]
----
--exclude Pods,Generated
----

Опция `--exclude` принимает список путей к файлам или каталогам, разделенных запятыми, для исключения из форматирования. Исключенные пути относительны к файлу конфигурации, содержащему команду `--exclude`. Исключенные пути могут включать подстановочные знаки, указанные с использованием синтаксиса Unix "Glob", как описано ниже.

Файлы конфигурации с именем `.swiftformat` будут обрабатываться автоматически, однако вы можете выбрать дополнительный файл конфигурации для использования при форматировании с помощью аргумента командной строки `--config "path/to/config/file"`. Файл конфигурации, выбранный с помощью `--config`, не обязательно должен называться `.swiftformat` и может находиться за пределами каталога проекта.

Формат файла конфигурации предназначен для редактирования вручную. Вы можете включать пустые строки для удобочитаемости, а также добавлять комментарии с помощью префикса-хеша (`#`), например:

[source]
----
# опции форматирования
--allman true
--indent tab # табы рулят!

# опции файлов
--exclude Pods

# правила
--disable elseOnSameLine,semicolons
----

Вы можете создать несколько разделов конфигурации в одном файле `.swiftformat`, чтобы применять разные опции форматирования к разным частям вашего проекта. Каждый раздел должен указывать шаблон glob `--filter`, чтобы определить, к каким файлам применяется конфигурация. Опции в этом разделе используются при форматировании файлов, соответствующих glob `--filter`, в дополнение к базовым опциям в файле.

[source]
----
--enable indent
--indent 4

[Tests]
--filter **/Tests/**
--enable noForceUnwrapInTests
--enable noForceTryInTests
--indent 2
----

Если вы предпочитаете не редактировать файл конфигурации вручную, вы можете использовать приложение SwiftFormat for Xcode для редактирования конфигурации и экспорта файла конфигурации. Вы также можете использовать команду `--infer-options` инструмента командной строки `swiftformat` для генерации файла конфигурации из вашего существующего проекта, вот так:

[source,bash]
----
$ cd /path/to/project
$ swiftformat --infer-options . --output .swiftformat
----

=== Линтинг

SwiftFormat в первую очередь разработан как форматер, а не как линтер, т.е. он предназначен для исправления вашего кода, а не для того, чтобы сообщать вам, что с ним не так. Однако иногда бывает полезно убедиться, что код отформатирован в контексте, где нежелательно его изменять.

Типичным примером может быть часть процесса CI (непрерывной интеграции), где вы можете захотеть иметь автоматизированный скрипт, который проверяет закоммиченный код на предмет нарушений стиля. Хотя вы можете использовать отдельный инструмент, такой как SwiftLint, для этого, имеет смысл иметь возможность проверять форматирование по тем же правилам, которые вы используете для его применения.

Чтобы запустить SwiftFormat как линтер, вы можете использовать опцию командной строки `--lint`:

[source,bash]
----
$ swiftformat --lint path/to/project
----

Это запускает те же правила, что и в режиме форматирования, и применяются все те же опции конфигурации, однако никакие файлы не будут изменены. Вместо этого SwiftFormat отформатирует каждый файл в памяти, а затем сравнит результат с вводом и сообщит о строках, которые требовали изменений.

Опция `--lint` похожа на `--dry-run`, но `--lint` возвращает предупреждения для каждой строки, которая требовала изменений, и вернет ненулевой код ошибки (см. Коды ошибок ниже), если будут обнаружены какие-либо изменения, что полезно, если вы хотите, чтобы он провалил шаг сборки на вашем CI-сервере.

Если вы предпочитаете, чтобы `--lint` не проваливал вашу сборку, вы можете использовать опцию `--lenient`, чтобы заставить SwiftFormat возвращать успех в режиме `--lint`, даже если были обнаружены проблемы с форматированием.

[source,bash]
----
$ swiftformat --lint --lenient path/to/project
----

По умолчанию `--lint` будет сообщать только о строках, требующих форматирования, но вы можете использовать дополнительный флаг `--verbose`, чтобы отобразить дополнительную информацию о том, какие файлы были проверены, даже если изменений не требовалось.

Если вы предпочитаете не видеть предупреждение для каждого изменения форматирования, вы можете использовать флаг `--quiet`, чтобы подавить весь вывод, кроме ошибок.

Иногда вы можете захотеть автоматически форматировать некоторые правила, но только проверять другие. Для этого используйте опцию `--lint-only` в вашем файле конфигурации, чтобы указать правила, которые должны применяться только в режиме `--lint`:

[source]
----
--rules braces,indent
--lint-only trailingClosures,unusedArguments
----