---
layout: default
title: Тема Hydejack
parent: Темы Jekyll
grand_parent: Jekyll & GitHub Pages
nav_order: 2
---

= Тема Hydejack

Hydejack — это бутиковая тема Jekyll для хакеров, нёрдов и ученых, с акцентом на персональные сайты, которые должны производить впечатление.

Она включает в себя блог, подходящий как для прозы, так и для технической документации, портфолио для демонстрации ваших проектов и шаблон резюме, который отлично выглядит в вебе и при печати.

Ваше полное присутствие в вебе — блог, портфолио и резюме.

== Персональный сайт, который не исчезнет

Hydejack на 100% построен на программном обеспечении с открытым исходным кодом и сам является открытым, за исключением частей PRO-версии. PRO-версия — это единовременный платеж, который дает вам право использовать ее вечно.

Hydejack — это полностью статические сайты. HTML. Все, что вам нужно, — это веб-сервер — любой веб-сервер — чтобы иметь профессиональное веб-присутствие на всю жизнь.

== Бесплатная тема для блога

Hydejack начинался как бесплатная тема для блога на Jekyll — и продолжает ею быть.

== Впечатляющее портфолио

Портфолио, которое гарантированно будет впечатляющим — независимо от того, что вы в него поместите.

== Резюме для печати

Получите резюме, которое выглядит одинаково везде — будь то в вебе, на мобильном устройстве, в печати или в PDF.

== Только Markdown

Пишите весь контент с помощью Markdown. Hydejack предоставляет вам дополнительные CSS-классы для стилизации вашего контента, не теряя совместимости с другими темами Jekyll.

== Только разметка

Hydejack может похвастаться множеством современного JavaScript, но не заблуждайтесь: в своей основе это все та же старая добрая веб-страница. Она работает без JavaScript, и вы даже можете просматривать ее в текстовом браузере, таком как w3m.

== Подсветка синтаксиса

Hydejack поддерживает подсветку синтаксиса, работающую на движке Rouge.

[source,html]
----
<!-- file: `_includes/my-body.html` -->
<script type="module">
  document.querySelector("hy-push-state").addEventListener("hy-push-state-load", () => {
    const supportsCodeHighlights = false; // TBD!!
  });
</script>
----

Блоки кода могут иметь имя файла и подпись.

== Красивая математика

Говорят, математика прекрасна — и с поддержкой математики в Hydejack она гарантированно будет выглядеть красиво. Hydejack использует KaTeX для эффективного рендеринга математических выражений.

== Особенности

Неполный список функций, включенных во все версии Hydejack:

* Адаптивный макет с уникальными дизайнерскими особенностями для каждого размера экрана.
* Обложки для создания потрясающего первого впечатления.
* Настраиваемая боковая панель и сенсорное выдвижное меню.
* Загрузка страниц в стиле одностраничного веб-приложения (SPA).
* Продвинутые FLIP-анимации footnote:[First-Last-Invert-Play. Техника кодирования для достижения производительных анимаций перехода страниц.], вдохновленные Material Design.
* Хороший результат в Google PageSpeed Score. footnote:[Фактическая скорость загрузки страницы зависит от вашего хостинг-провайдера, местоположения, разрешения и формата изображений, использования сторонних плагинов и других факторов.]
* Подсветка синтаксиса на движке Rouge.
* Математические блоки LaTeX, отображаемые с помощью KaTeX или MathJax на ваш выбор.
* "Мягко" закодированные метки: изменяйте формулировки или переводите на другие языки через один файл.
* Поддержка категорий и тегов.
* Раздел автора под каждой статьей и поддержка нескольких авторов.
* Встроенные иконки для многих социальных сетей.
* Простой и семантический HTML + структурированные данные.
* Работает с GitHub Pages "из коробки". footnote:[Применяются некоторые ограничения, в частности, необходимость использовать MathJax вместо KaTeX для рендеринга математических блоков.]

== Скачать

Существует две версии Hydejack: бесплатная версия включает базовую функциональность для ведения блога и большинство функций Hydejack, таких как динамическая загрузка страниц и продвинутые анимации.

PRO-версия включает дополнительные функции для профессионалов, такие как портфолио, резюме, темный режим, формы, встроенный поиск и настраиваемые баннеры о cookie.

В таблице ниже показано, что включено в каждую версию:

[cols="1,1,1",options="header"]
|===
| | Free | PRO
| Блог | ✔ | ✔
| Особенности | ✔ | ✔
| Документация | ✔ | ✔
| Темный режим | ✔ | ✔
| Портфолио | | ✔
| Резюме для печати | | ✔
| Встроенный поиск | | ✔
| Пользовательские формы | | ✔
| Сеточная верстка | | ✔
| Офлайн-поддержка | | ✔
| Содержание footnote:[Некоторые ограничения применяются.] | | ✔
| Баннер о cookie | | ✔
| Без брендинга Hydejack | | ✔
|===