---
layout: default
title: Тема Chirpy
parent: Темы Jekyll
grand_parent: Jekyll & GitHub Pages
nav_order: 4
---

= Тема Chirpy

При установке темы Chirpy через RubyGems.org, Jekyll может читать файлы только из папок `_data`, `_layouts`, `_includes`, `_sass` и `assets`, а также небольшую часть опций из файла `_config.yml` из гема темы. Если вы когда-либо устанавливали этот гем темы, вы можете использовать команду `bundle info --path jekyll-theme-chirpy`, чтобы найти эти файлы.

Команда Jekyll утверждает, что это сделано для того, чтобы "оставить мяч на стороне пользователя", но это также приводит к тому, что пользователи не могут наслаждаться готовым к использованию опытом при использовании многофункциональных тем.

Чтобы в полной мере использовать все возможности Chirpy, вам необходимо скопировать другие критически важные файлы из гема темы на ваш сайт Jekyll. Ниже приведен список целей:

[source,text]
----
.
├── _config.yml
├── _plugins
├── _tabs
└── index.html
----

Чтобы сэкономить ваше время, а также на случай, если вы потеряете какие-либо файлы при копировании, мы извлекли эти файлы/конфигурации последней версии темы Chirpy и рабочего процесса CD сюда, чтобы вы могли начать писать за считанные минуты.