name: 'Build for Testing'
description: 'Builds the project for testing and creates an xctestrun artifact.'

runs:
  using: "composite"
  steps:
    - name: Install Dependencies
      uses: ./.github/actions/setup-ios-environment

    - name: Install CocoaPods dependencies
      shell: bash
      run: pod install

    - name: Run Unit Tests
      shell: bash
      run: |
        # Find an available iPhone simulator
        DESTINATION_UDID=$(xcrun simctl list devices available -j | jq -r '.devices | .[] | .[] | select(.name | startswith("iPhone")) | .udid' | head -n 1)
        if [ -z "$DESTINATION_UDID" ]; then
          echo "::error::No available iPhone simulator found."
          exit 1
        fi
        echo "Using simulator with UDID: $DESTINATION_UDID"

        xcodebuild build-for-testing \
          -workspace "SDET Demo App.xcworkspace" \
          -scheme "AllTests" \
          -destination "id=$DESTINATION_UDID" \
          -derivedDataPath build 