= Настройка фавиконок
:toc:
:lang: ru

Фавиконки для темы Chirpy размещены в каталоге `assets/img/favicons/`. Вы можете заменить их своими собственными. Следующие разделы помогут вам создать и заменить фавиконки по умолчанию.

== Генерация фавиконок

Подготовьте квадратное изображение (PNG, JPG или SVG) размером 512x512 пикселей или больше, а затем перейдите к онлайн-инструменту link:https://realfavicongenerator.net/[Real Favicon Generator] и нажмите кнопку *Select your Favicon image*, чтобы загрузить ваш файл изображения.

На следующем шаге веб-страница покажет все сценарии использования. Вы можете оставить настройки по умолчанию, прокрутить страницу до конца и нажать кнопку *Generate your Favicons and HTML code*, чтобы сгенерировать фавиконки.

== Загрузка и замена

На следующей странице нажмите на кнопку *Favicon package*, чтобы загрузить сгенерированный пакет.

Распакуйте его и удалите из извлеченных файлов следующий файл:

* `site.webmanifest`

Затем скопируйте оставшиеся файлы изображений (.PNG, .ICO и .SVG) и замените ими оригинальные файлы в каталоге `assets/img/favicons/` вашего сайта Jekyll. Если на вашем сайте Jekyll еще нет этого каталога, просто создайте его.

Следующая таблица поможет вам понять, какие файлы нужно использовать:

[cols="1,1", options="header"]
|===
| Файл(ы) | Действие

| `*.PNG` | ✓ Сохранить
| `*.ICO` | ✓ Сохранить
| `*.SVG` | ✓ Сохранить
| `site.webmanifest` | ✗ Удалить
|===

При следующей сборке сайта фавиконки будут заменены на ваши собственные.