= Начало работы с Chirpy
:author: Cotes Chung
:revdate: 2019-08-09
:last-update-date: 2025-02-06
:toc:
:lang: ru

Начните работу с основами Chirpy в этом подробном обзоре. Вы узнаете, как установить, настроить и использовать ваш первый веб-сайт на основе Chirpy, а также как развернуть его на веб-сервере.

== Создание репозитория сайта

При создании репозитория у вас есть два варианта в зависимости от ваших потребностей:

=== Вариант 1. Использование стартера (рекомендуется)

Этот подход упрощает обновления, изолирует ненужные файлы и идеально подходит для пользователей, которые хотят сосредоточиться на написании контента с минимальной настройкой.

. Войдите в GitHub и перейдите к стартеру.
. Нажмите кнопку *Use this template*, а затем выберите *Create a new repository*.
. Назовите новый репозиторий `<username>.github.io`, заменив `username` вашим именем пользователя GitHub в нижнем регистре.

=== Вариант 2. Форк темы

Этот подход удобен для изменения функций или дизайна интерфейса, но создает проблемы при обновлениях. Поэтому не пытайтесь использовать его, если вы не знакомы с Jekyll и не планируете серьезно изменять эту тему.

. Войдите в GitHub.
. Сделайте форк репозитория темы.
. Назовите новый репозиторий `<username>.github.io`, заменив `username` вашим именем пользователя GitHub в нижнем регистре.

== Настройка окружения

После создания репозитория пора настроить среду разработки. Существует два основных метода:

=== Использование Dev Containers (рекомендуется для Windows)

Dev Containers предлагают изолированную среду с использованием Docker, что предотвращает конфликты с вашей системой и гарантирует, что все зависимости управляются внутри контейнера.

*Шаги:*

. Установите Docker:
** В Windows/macOS установите Docker Desktop.
** В Linux установите Docker Engine.
. Установите VS Code и расширение Dev Containers.
. Клонируйте ваш репозиторий:
** Для Docker Desktop: запустите VS Code и клонируйте репозиторий в том контейнера (container volume).
** Для Docker Engine: клонируйте репозиторий локально, затем откройте его в контейнере через VS Code.
. Дождитесь завершения настройки Dev Containers.

=== Нативная установка (рекомендуется для Unix-подобных ОС)

Для Unix-подобных систем вы можете настроить среду нативно для оптимальной производительности, хотя вы также можете использовать Dev Containers в качестве альтернативы.

*Шаги:*

. Следуйте руководству по установке Jekyll, чтобы установить Jekyll, и убедитесь, что Git установлен.
. Клонируйте репозиторий на свой локальный компьютер.
. Если вы сделали форк темы, установите Node.js и выполните `bash tools/init.sh` в корневом каталоге для инициализации репозитория.
. Выполните команду `bundle` в корне вашего репозитория, чтобы установить зависимости.

== Использование

=== Запуск сервера Jekyll

Чтобы запустить сайт локально, используйте следующую команду:

[source,bash]
----
$ bundle exec jekyll serve
----

Если вы используете Dev Containers, вы должны выполнить эту команду в терминале VS Code.

Через несколько секунд локальный сервер будет доступен по адресу `http://127.0.0.1:4000`.

== Конфигурация

При необходимости обновите переменные в файле `_config.yml`. Некоторые типичные опции включают:

* `url`
* `avatar`
* `timezone`
* `lang`

=== Опции социальных контактов

Опции социальных контактов отображаются внизу боковой панели. Вы можете включить или отключить определенные контакты в файле `_data/contact.yml`.

=== Кастомизация таблицы стилей

Чтобы настроить таблицу стилей, скопируйте файл темы `assets/css/jekyll-theme-chirpy.scss` в тот же путь на вашем сайте Jekyll и добавьте свои пользовательские стили в конец файла.

=== Кастомизация статических ресурсов

Конфигурация статических ресурсов была введена в версии 5.1.0. CDN для статических ресурсов определяется в `_data/origin/cors.yml`. Вы можете заменить некоторые из них в зависимости от условий сети в регионе, где опубликован ваш сайт.

Если вы предпочитаете размещать статические ресурсы самостоятельно, обратитесь к репозиторию `chirpy-static-assets`.

== Развертывание

Перед развертыванием проверьте файл `_config.yml` и убедитесь, что `url` настроен правильно. Если вы предпочитаете сайт проекта и не используете собственный домен, или если вы хотите посещать свой сайт с базовым URL на веб-сервере, отличном от GitHub Pages, не забудьте установить `baseurl` на имя вашего проекта, начиная со слэша, например, `/project-name`.

Теперь вы можете выбрать ОДИН из следующих методов для развертывания вашего сайта Jekyll.

=== Развертывание с помощью Github Actions

Подготовьте следующее:

. Если вы используете бесплатный план GitHub, держите репозиторий вашего сайта публичным.
. Если вы закоммитили `Gemfile.lock` в репозиторий, и ваша локальная машина не работает под управлением Linux, обновите список платформ в lock-файле:
+
[source,bash]
----
$ bundle lock --add-platform x86_64-linux
----

Затем настройте сервис Pages:

Перейдите в свой репозиторий на GitHub. Выберите вкладку *Settings*, затем нажмите *Pages* на левой навигационной панели. В разделе *Source* (под *Build and deployment*) выберите *GitHub Actions* из выпадающего меню.

Отправьте любые коммиты в GitHub, чтобы запустить рабочий процесс Actions. На вкладке *Actions* вашего репозитория вы должны увидеть запущенный рабочий процесс *Build and Deploy*. Как только сборка будет завершена и успешна, сайт будет развернут автоматически.

Теперь вы можете посетить URL-адрес, предоставленный GitHub, чтобы получить доступ к вашему сайту.

=== Ручная сборка и развертывание

Для серверов с собственным хостингом вам потребуется собрать сайт на локальной машине, а затем загрузить файлы сайта на сервер.

Перейдите в корень исходного проекта и соберите свой сайт с помощью следующей команды:

[source,bash]
----
$ JEKYLL_ENV=production bundle exec jekyll b
----

Если вы не указали путь вывода, сгенерированные файлы сайта будут помещены в папку `_site` в корневом каталоге проекта. Загрузите эти файлы на ваш целевой сервер.