name: 'Run Unit Tests'
description: 'Runs unit tests, generates raw coverage data and test results.'

runs:
  using: "composite"
  steps:
    - name: Download build artifact
      uses: actions/download-artifact@v4
      with:
        name: xctestrun-build
        path: build

    - name: Run Unit Tests
      shell: bash
      run: |
        # Find an available iPhone simulator
        DESTINATION_UDID=$(xcrun simctl list devices available -j | jq -r '.devices | .[] | .[] | select(.name | startswith("iPhone")) | .udid' | head -n 1)
        if [ -z "$DESTINATION_UDID" ]; then
          echo "::error::No available iPhone simulator found."
          exit 1
        fi
        echo "Using simulator with UDID: $DESTINATION_UDID"

        XCTESTRUN_FILE=$(find build/Build/Products -name "AllTests*.xctestrun")
        echo "Found xctestrun file at: $XCTESTRUN_FILE"
        xcodebuild test-without-building \
          -xctestrun "$XCTESTRUN_FILE" \
          -destination "id=$DESTINATION_UDID" \
          -only-testing:Demo\ AppTests \
          -resultBundlePath "unit-test-results/TestResults.xcresult"

    - name: Upload unit test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: unit-test-results
        path: unit-test-results/
    