name: 'Run UI Tests'
description: 'Runs UI tests and generates test results.'

runs:
  using: "composite"
  steps:
    - name: Download build artifact
      uses: actions/download-artifact@v4
      with:
        name: xctestrun-build
        path: build

    - name: Run UI tests
      shell: bash
      run: |
        # Find an available iPhone simulator
        DESTINATION_UDID=$(xcrun simctl list devices available -j | jq -r '.devices | .[] | .[] | select(.name | startswith("iPhone")) | .udid' | head -n 1)
        if [ -z "$DESTINATION_UDID" ]; then
          echo "::error::No available iPhone simulator found."
          exit 1
        fi
        echo "Using simulator with UDID: $DESTINATION_UDID"

        # Run tests on the found simulator
        XCTESTRUN_FILE=$(find build/Build/Products -name "AllTests*.xctestrun")
        xcodebuild test-without-building \
          -xctestrun "$XCTESTRUN_FILE" \
          -destination "id=$DESTINATION_UDID" \
          -only-testing:SDET\ Demo\ AppUITests \
          -resultBundlePath "ui-test-results/TestResults.xcresult"

    - name: Upload UI test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: ui-test-results
        path: ui-test-results/