:doctype: book
:encoding: utf-8
:lang: ru
:toc: left
:toclevels: 4
:sectnums:
= allure quality-gate

Команда `allure quality-gate` проверяет результаты тестов на соответствие правилам "quality gates", определенным в конфигурации. Если результаты не соответствуют заданным критериям (например, процент успешных тестов ниже порогового значения), команда завершится с кодом ошибки.

== Синтаксис

[source,bash]
----
$ allure quality-gate [options] [шаблон_пути_к_результатам]
----
По умолчанию команда ищет результаты в директориях, соответствующих шаблону `**/allure-results`.

== Опции

`--config, -c <путь>`::
Путь к файлу конфигурации Allure.

`--fast-fail`::
Принудительно завершает команду с ошибкой при любом нарушении правил.

`--max-failures <число>`::
Максимально допустимое количество нарушений правил перед провалом команды.

`--min-tests-count <число>`::
Минимальное количество тестов, которое должно быть выполнено перед проверкой quality gate.

`--success-rate <число>`::
Минимальный процент успешных тестов, необходимый для прохождения quality gate.

`--known-issues <путь>`::
Путь к файлу известных проблем. Обновляет файл и помещает упавшие тесты в карантин, если указано.

`--cwd <путь>`::
Рабочая директория для запуска команды. По умолчанию используется текущая рабочая директория.

== Примеры

.Проверить результаты тестов в директории `./allure-results`:
[source,bash]
----
$ allure quality-gate ./allure-results
----

.Проверить результаты тестов, используя кастомный файл конфигурации:
[source,bash]
----
$ allure quality-gate ./allure-results --config custom-config.js
----