:doctype: book
:encoding: utf-8
:lang: ru
:toc: left
:toclevels: 4
:sectnums:
= allure open

Команда `allure open` запускает локальный веб-сервер для отображения сгенерированного HTML-отчета и открывает его в браузере по умолчанию.

== Синтаксис

[source,bash]
----
$ allure open [options] [путь_к_директории_с_отчетом]
----
Если путь не указан, используется директория по умолчанию (`allure-report`).

== Опции

`--config, -c <путь>`::
Путь к файлу конфигурации Allure.

`--port <номер_порта>`::
Порт, на котором будет запущен сервер. Если не указан, используется случайный свободный порт.

`--live`::
Включает режим "живой" перезагрузки. Страницы отчета будут автоматически обновляться при любых изменениях в файлах директории с отчетом.

`--cwd <путь>`::
Рабочая директория для запуска команды. По умолчанию используется текущая рабочая директория.

== Примеры

.Открыть отчет из директории по умолчанию:
[source,bash]
----
$ allure open
----

.Открыть отчет из директории `custom-report` на порту 8080 с "живой" перезагрузкой:
[source,bash]
----
$ allure open custom-report --port 8080 --live
----