:doctype: book
:encoding: utf-8
:lang: ru
:toc: left
:toclevels: 4
:sectnums:
= allure classic

Команда `allure classic` генерирует отчет Allure Classic из указанной директории с результатами Allure.

== Синтаксис

[source,bash]
----
$ allure classic [options] <путь_к_директории_с_результатами>
----

== Опции

`--config, -c <путь>`::
Путь к файлу конфигурации Allure.

`--cwd <путь>`::
Рабочая директория для запуска команды. По умолчанию используется текущая рабочая директория.

`--output, -o <путь>`::
Имя директории для вывода отчета. Также принимаются абсолютные пути.

`--report-name, --name <имя>`::
Имя отчета.

`--report-language, --lang <язык>`::
Язык отчета по умолчанию. По умолчанию используется язык операционной системы.

`--single-file`::
Генерировать отчет в виде одного HTML-файла.

`--history-path, -h <путь>`::
Путь к файлу истории для сохранения трендов между запусками.

`--known-issues <путь>`::
Путь к файлу известных проблем. Обновляет файл и помещает упавшие тесты в карантин, если указано.

== Примеры

.Сгенерировать отчет из директории `./allure-results`:
[source,bash]
----
$ allure classic ./allure-results
----

.Сгенерировать отчет из `./allure-results` в директорию `custom-report`:
[source,bash]
----
$ allure classic ./allure-results --output custom-report
----