:doctype: book
:encoding: utf-8
:lang: ru
:toc: left
:toclevels: 4
:sectnums:
= allure awesome

Команда `allure awesome` генерирует отчет Allure Awesome из указанной директории с результатами Allure.

== Синтаксис

[source,bash]
----
$ allure awesome [options] <путь_к_директории_с_результатами>
----

== Опции

`--config, -c <путь>`::
Путь к файлу конфигурации Allure.

`--cwd <путь>`::
Рабочая директория для запуска команды. По умолчанию используется текущая рабочая директория.

`--output, -o <путь>`::
Имя директории для вывода отчета. Также принимаются абсолютные пути.

`--report-name, --name <имя>`::
Имя отчета.

`--single-file`::
Генерировать отчет в виде одного HTML-файла.

`--logo <путь>`::
Путь к логотипу отчета, который будет отображаться в заголовке.

`--theme <тема>`::
Тема отчета по умолчанию. По умолчанию используется тема ОС (`light` или `dark`).

`--report-language, --lang <язык>`::
Язык отчета по умолчанию. По умолчанию используется язык операционной системы.

`--history-path, -h <путь>`::
Путь к файлу истории для сохранения трендов между запусками.

`--known-issues <путь>`::
Путь к файлу известных проблем. Обновляет файл и помещает упавшие тесты в карантин, если указано.

`--group-by, -g <метки>`::
Группировать результаты тестов по меткам (labels). Метки должны быть разделены запятыми.

== Примеры

.Сгенерировать отчет из директории `./allure-results`:
[source,bash]
----
$ allure awesome ./allure-results
----

.Сгенерировать отчет из `./allure-results` в директорию `custom-report`:
[source,bash]
----
$ allure awesome ./allure-results --output custom-report
----