:doctype: book
:encoding: utf-8
:lang: ru
:toc: left
:toclevels: 4
:sectnums:
= allure dashboard

Команда `allure dashboard` генерирует отчет Allure Dashboard из указанной директории с результатами Allure.

== Синтаксис

[source,bash]
----
$ allure dashboard [options] <путь_к_директории_с_результатами>
----

== Опции

`--config, -c <путь>`::
Путь к файлу конфигурации Allure.

`--cwd <путь>`::
Рабочая директория для запуска команды. По умолчанию используется текущая рабочая директория.

`--output, -o <путь>`::
Имя директории для вывода отчета. Также принимаются абсолютные пути.

`--report-name, --name <имя>`::
Имя отчета.

`--single-file`::
Генерировать отчет в виде одного HTML-файла.

`--logo <путь>`::
Путь к логотипу отчета, который будет отображаться в заголовке.

`--theme <тема>`::
Тема отчета по умолчанию. По умолчанию используется тема ОС (`light` или `dark`).

`--report-language, --lang <язык>`::
Язык отчета по умолчанию. По умолчанию используется язык операционной системы.

== Примеры

.Сгенерировать отчет из директории `./allure-results`:
[source,bash]
----
$ allure dashboard ./allure-results
----

.Сгенерировать отчет из `./allure-results` в директорию `custom-report`:
[source,bash]
----
$ allure dashboard ./allure-results --output custom-report
----