:doctype: book
:encoding: utf-8
:lang: ru
:toc: left
:toclevels: 4
:sectnums:
= allure watch

Команда `allure watch` отслеживает изменения в директории с результатами Allure и обновляет отчет в реальном времени. Это очень удобно во время локальной разработки и отладки тестов, так как отчет автоматически пересобирается и обновляется в браузере.

== Синтаксис

[source,bash]
----
$ allure watch [options] <путь_к_директории_с_результатами>
----

== Опции

`--config, -c <путь>`::
Путь к файлу конфигурации Allure.

`--cwd <путь>`::
Рабочая директория для запуска команды. По умолчанию используется текущая рабочая директория.

`--output, -o <путь>`::
Директория для вывода отчета. По умолчанию `./allure-report`.

`--report-name, --name <имя>`::
Имя отчета. По умолчанию "Allure Report".

`--port <номер_порта>`::
Порт, на котором будет запущен сервер с отчетом. По умолчанию используется случайный свободный порт.

== Примеры

.Отслеживать изменения в директории `./allure-results`:
[source,bash]
----
$ allure watch ./allure-results
----

.Отслеживать изменения в `./allure-results` и отображать отчет на порту 8080:
[source,bash]
----
$ allure watch ./allure-results --port 8080
----