:doctype: book
:encoding: utf-8
:lang: ru
:toc: left
:toclevels: 4
:sectnums:
= allure run

Команда `allure run` запускает указанную команду (например, для запуска тестов) и автоматически собирает результаты Allure.

== Синтаксис

[source,bash]
----
$ allure run [options] -- <command>
----

NOTE: Обратите внимание на `--` перед командой, которую вы хотите запустить. Это стандартный синтаксис для разделения опций команды `allure run` от самой запускаемой команды и ее аргументов.

== Опции

`--config, -c <путь>`::
Путь к файлу конфигурации Allure.

`--cwd <путь>`::
Рабочая директория для запуска команды. По умолчанию используется текущая рабочая директория.

`--output, -o <путь>`::
Путь для сохранения сгенерированного отчета. По умолчанию `./allure-report`.

`--report-name, --name <имя>`::
Имя для отчета. По умолчанию "Allure Report".

`--rerun <число>`::
Количество перезапусков для упавших тестов. По умолчанию `0`.

`--silent`::
Не выводить логи процесса в консоль.

`--ignore-logs`::
Предотвратить прикрепление логов к отчету.

`--stage <имя>`::
Запускает тесты в "stage" режиме для сбора результатов в архив с указанным именем.

`--environment <имя>`::
Принудительно устанавливает определенное окружение для всех тестов в запуске. Это значение имеет более высокий приоритет, чем окружение, определенное в файле конфигурации.

== Примеры

.Запустить `npm run test` и собрать результаты Allure:
[source,bash]
----
$ allure run -- npm run test
----

.Запустить `npm run test` и перезапустить упавшие тесты до 3 раз:
[source,bash]
----
$ allure run --rerun 3 -- npm run test
----

.Запустить тесты в режиме "stage" с именем `my-stage`:
[source,bash]
----
$ allure run --stage=my-stage -- npm run test
----