title: [Project Quality Report]
description: [Provide SWIFT project with different kinds of tests with reporting]

remote_theme: shikofx/jekyll-theme-minimal

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
