name: Code analysis

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs: 
  swiftlint_analysis:
    name: Run SwiftLint
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SwiftLint
        run: brew install swiftlint

      - name: Run SwiftLint
        run: swiftlint --strict

  clang_analysis:
    name: Run Clang Static Analyzer
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pod install --repo-update

      - name: Run Clang Static Analyzer
        run: xcodebuild analyze -workspace "SDET Demo App.xcworkspace" -scheme "SDET Demo App" -destination 'platform=iOS Simulator,name=iPhone 15'