name: Build Release App

on:
  workflow_call:

jobs:
  build_app:
    name: Release App
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        uses: ./.github/actions/setup-ios-environment

      - name: Build .app
        run: |
          PODS_PODFILE_DIR_PATH="${{ github.workspace }}" xcodebuild build \
            -workspace "SDET Demo App.xcworkspace" \
            -scheme "SDET Demo App" \
            -sdk iphonesimulator \
            -configuration Release \
            -derivedDataPath build

      - name: Create .app artifact
        run: |
          ditto -c -k --sequesterRsrc --keepParent "build/Build/Products/Release-iphonesimulator/SDET Demo App.app" "SDET-Demo-App.zip"

      - name: Upload .app artifact
        uses: actions/upload-artifact@v4
        with:
          name: sdet-demo-app
          path: SDET-Demo-App.zip
          retention-days: 7