name: IOS-DEMO-CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  analysis:
    name: Code Analysis
    uses: ./.github/workflows/static-analysis.yml

  # unit_tests:
  #   name: Unit Tests
  #   needs: [analysis]
  #   uses: ./.github/workflows/unit-tests.yml

  # build_app:
    # name: Build
    # needs: [unit_tests]
    # uses: ./.github/workflows/build-archive.yml
  
  deploy_reports:
    name: Reports
    needs: [analysis]
    if: always()
    uses: ./.github/workflows/deploy-reports.yml