name: IOS-DEMO

on:
  push:
    branches:
      - '**'
      
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  swiftlint_analysis:
    name: Static Analysis - SwiftLint
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Swiftlint Report
        uses: ./.github/actions/swiftlint-report
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  swiftformat_analysis:
    name: Static Analysis - SwiftFormat
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create SwiftFormat Report
        uses: ./.github/actions/swiftformat-report
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

# build_for_testing:
  #   name: Build for Testing
  #   needs: [swiftlint_analysis, swiftformat_analysis]
  #   runs-on: macos-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Cache Xcode DerivedData
  #       uses: actions/cache@v4
  #       with:
  #         path: build
  #         key: ${{ runner.os }}-xcode-deriveddata-${{ hashFiles('**/Podfile.lock') }}-${{ hashFiles('**/*.swift') }}
  #         restore-keys: |
  #           ${{ runner.os }}-xcode-deriveddata-${{ hashFiles('**/Podfile.lock') }}-
  #           ${{ runner.os }}-xcode-deriveddata-

  #     - name: Build for Testing
  #       uses: ./.github/actions/build-for-testing

  #     - name: Upload artifact
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: xctestrun-build
  #         path: build
  #         retention-days: 1

  unit_tests:
    name: Unit Tests
    needs: [
      swiftlint_analysis, 
      swiftformat_analysis
    ]
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests and generate report
        uses: ./.github/actions/test-unit

  generate_coverage_report:
    name: Report - Coverage
    needs: unit_tests
    if: always()
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download raw test results
        uses: actions/download-artifact@v4
        with:
          name: test-results
          path: .

      - name: Generate HTML Report
        uses: ./.github/actions/swift-coverage-report
        with: 
          test-results-path: TestResults.xcresult
          github-token: ${{ secrets.GITHUB_TOKEN }}

  generate_allure_report:
    name: Report - Test
    needs: unit_tests
    if: always()
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download test results
        uses: actions/download-artifact@v4
        with:
          name: test-results
          path: .

      - name: Create Allure Report page
        uses: ./.github/actions/allure-report
        with:
          test-results-path: TestResults.xcresult
          github-token: ${{ secrets.GITHUB_TOKEN }}

  build_site:
    name: Build Reports Site
    needs: [
      generate_coverage_report,
      generate_allure_report
    ]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project repository
        uses: actions/checkout@v4

      - name: Checkout github-pages repository
        uses: actions/checkout@v4
        with:
          repository: shikofx/github-pages
          path: gh-pages-repo
          ref: ${{ github.event.repository.name }} # Указываем, что работать нужно с веткой, названной как наш репозиторий
          token: ${{ secrets.GH_PAGES_PAT }} 

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: .artifacts
      
      - name: Prepare and publish raw data
        run: |
          # Определяем общий статус предыдущих jobs
          CONCLUSION="success"
          # Статус всего билда определяется успехом или провалом ключевого job'а - unit_tests.
          if [[ "${{ needs.unit_tests.result }}" == "failure" ]]; then
            CONCLUSION="failure"
          fi
          
          # Вызываем скрипт, который создает папки и мета-файлы
          bash ./.github/scripts/create-publish-data.sh \
            "gh-pages-repo" \
            ".artifacts" \
            "${{ github.ref_name }}" \
            "${{ github.run_number }}" \
            "${{ github.sha }}" \
            "${{ github.actor }}" \
            "$CONCLUSION" \
            "${{ github.event.repository.name }}"
      
      - name: Commit and Push data to github-pages
        run: |
          cd gh-pages-repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          # Коммитим и пушим изменения в целевую ветку
          if ! git diff --staged --quiet; then
            git commit -m "Add report for build ${{ github.run_number }} from ${{ github.repository }}"
            git push
          else
            echo "No changes to commit."
          fi
      
      - name: Show report URL
        run: |
          echo "================================================================="
          echo "Data has been published to the shikofx/github-pages repository."
          echo "The report will be available at the following URL after the site is built:"
          echo "https://shikofx.github.io/github-pages/projects/${{ github.event.repository.name }}/$(echo ${{ github.ref_name }} | sed 's/\//-/g')/${{ github.run_number }}/"
          echo "================================================================="

  # build_app:
  #   name: Build App
  #   needs: [unit_tests]
  #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
  #   runs-on: macos-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Build and Archive
  #       uses: ./.github/actions/build-app

  #     - name: Upload .app artifact
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: sdet-demo-app
  #         path: SDET-Demo-App.zip
  #         retention-days: 7
 
  
