name: SDET-IOS-DEMO CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs: 
  test:
    name: Build and Analyze
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check Xcode version
        run: xcodebuild -version