name: Static Analysis

on:
  workflow_call:

jobs:
  swiftlint_analysis:
    name: SwiftLint
    runs-on: macos-latest
    steps:
      - name: Environment Variables
        run: env | sort
        
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        uses: ./.github/actions/setup-ios-environment

      - name: Run SwiftLint
        run: swiftlint lint --reporter json > swiftlint-report.json
        continue-on-error: true

      - name: Upload SwiftLint artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: swiftlint-report
          path: swiftlint-report.json
          retention-days: 7

  swiftformat_analysis:
    name: SwiftFormat
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        uses: ./.github/actions/setup-ios-environment

      - name: Run SwiftFormat (Lint Mode)
        id: swiftformat_run
        run: |
          swiftformat . --reporter json > swiftformat-report.json
        continue-on-error: true

      - name: Upload SwiftFormat artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: swiftformat-report
          path: swiftformat-report.json
          retention-days: 7