name: Reusable - Unit Tests

on:
  workflow_call:

jobs:
  run_unit_tests:
    name: Run
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        uses: ./.github/actions/setup-ios-environment

      - name: Run tests
        run: |
          PODS_PODFILE_DIR_PATH="${{ github.workspace }}" xcodebuild test \
            -workspace "SDET Demo App.xcworkspace" \
            -scheme "SDET Demo App" \
            -destination 'platform=iOS Simulator,name=iPhone SE (3rd generation),OS=latest'